services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/Caddyfile:/etc/caddy/Caddyfile
      - ./data/caddy_data:/data
      - ./data/caddy_config:/config
    environment:
      - CADDY_ACCEPT_EULA=true
